### ISSUE TITLE
[ADMIN] - Set up CI/CD and Infra

### ISSUE THREAD

**Issue by adam-fallon** [adam-fallon/HouseHistory#17]
We need to decide how to deploy the application.

Proposed architecture (this may change during this ticket)

![Image](https://github.com/adam-fallon/HouseHistory/assets/103489648/c8dab5d2-68ba-4a49-ba6d-35e0337f9c9c)

We have two applications;
- Web
- API

And they will both be docker containers. Pick automated, cheap method of deploying these applications as containers.

Some things to consider;
- They need to talk to each other. It would be great if the API could stay off the public internet and only allow communication from the webapp, but it's fine if we can't get that working.
- The API very likely needs to talk to a database and/or auth provider
- There needs to be a way to communicate with the web app over the public internet

When this method is chosen, write up the information in this issue and then as part of this ticket;
- Make sure to plan for the case where the host dies, we should have an automated way of redeploying either to the same provider on a different host.
- Would be ideal if we could write a Github Action that can do this deploy anytime we push to the main branch

## Additional Links
- [App Service Tutorial](https://www.youtube.com/watch?v=4BwyqmRTrx8)
- [App Service Containers Deploy using Github Actions](https://learn.microsoft.com/en-us/azure/app-service/deploy-container-github-action?tabs=publish-profile)
- [Pricing Calculator for this setup](https://azure.com/e/a8956a4a84af46d093b30fe9e911a8eb)

## Tasks
- [x] Take the web container, deploy it to an App Service.
- [x] Take the API container, deploy it to an App Service.
- [x] Create Github Action to autodeploy
- [x] Hit the API and Web via their public URL

**Comment by adam-fallon** [comment]
We used App Services from Azure.

The process works via Github Actions, and when you push to main it will build the docker image for each app and push to Azure Container Registry.

This allows for automated build and deploy in CI.

## Links
- [House History Web - App Service](https://portal.azure.com/#@adamfallon.com/resource/subscriptions/b21288f1-685d-4016-8dec-862638c5d92c/resourceGroups/househistory/providers/Microsoft.Web/sites/househistoryapp/appServices)
- [House History API - App Service](https://portal.azure.com/#@adamfallon.com/resource/subscriptions/b21288f1-685d-4016-8dec-862638c5d92c/resourceGroups/househistory/providers/Microsoft.Web/sites/househistoryapi/appServices)
- [House History Container Registry](https://portal.azure.com/#@adamfallon.com/resource/subscriptions/b21288f1-685d-4016-8dec-862638c5d92c/resourceGroups/househistory/providers/Microsoft.ContainerRegistry/registries/adamfallon/overview)
